#!/usr/bin/env python3
"""Generate a reproducible budget-constrained MLP pattern bank."""

import argparse
import random
from pathlib import Path


def parse_csv_ints(text):
    return [int(x.strip()) for x in text.split(",") if x.strip()]


def hamming(a, b):
    return sum(x != y for x, y in zip(a, b))


def max_zero_run(pattern):
    best = cur = 0
    for value in pattern:
        if value:
            cur = 0
        else:
            cur += 1
            best = max(best, cur)
    return best


def has_depth_coverage(pattern):
    groups = (pattern[:4], pattern[4:8], pattern[8:12])
    return all(any(group) for group in groups)


def sample_pattern(depth, active, rng):
    indices = rng.sample(range(depth), active)
    pattern = [0] * depth
    for idx in indices:
        pattern[idx] = 1
    return pattern


def generate_patterns(depth, active_counts, seed, min_hamming, max_zero):
    if depth != 12:
        raise ValueError("The current generator assumes ViT-S depth 12.")

    rng = random.Random(seed)
    patterns = {}
    existing = []
    counters = {}

    for active in active_counts:
        if active == depth:
            name = "full"
            pattern = [1] * depth
        else:
            for _ in range(10000):
                pattern = sample_pattern(depth, active, rng)
                if not has_depth_coverage(pattern):
                    continue
                if max_zero_run(pattern) > max_zero:
                    continue
                if existing and min(hamming(pattern, prev) for prev in existing) < min_hamming:
                    continue
                break
            else:
                raise RuntimeError(f"Could not sample a valid pattern with {active} active MLPs.")

            counters[active] = counters.get(active, 0) + 1
            name = f"rand{active}_{counters[active]:02d}"

        patterns[name] = pattern
        existing.append(pattern)

    return patterns


def write_yaml(patterns, output):
    output.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by scripts/generate_random_pattern_bank.py.",
        "# 1 means Attention + MLP, 0 means Attention only.",
    ]
    for name, pattern in patterns.items():
        lines.append(f"{name}: [{','.join(str(x) for x in pattern)}]")
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="configs/pattern_banks/random_budget6_bank12_seed42.yml")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--depth", type=int, default=12)
    parser.add_argument(
        "--active-counts",
        default="4,4,4,4,6,6,6,6,6,8,8,12",
        help="Comma-separated active MLP counts. Default averages to 6.17 for 12 patterns.",
    )
    parser.add_argument("--min-hamming", type=int, default=3)
    parser.add_argument("--max-zero-run", type=int, default=4)
    args = parser.parse_args()

    active_counts = parse_csv_ints(args.active_counts)
    patterns = generate_patterns(args.depth, active_counts, args.seed, args.min_hamming, args.max_zero_run)
    write_yaml(patterns, Path(args.output))

    avg_active = sum(sum(p) for p in patterns.values()) / len(patterns)
    print(f"Wrote {len(patterns)} patterns to {args.output}")
    print(f"Average active MLP count: {avg_active:.3f}")


if __name__ == "__main__":
    main()
